use printpdf::*;
use std::fs::File;
use std::io::BufWriter;
use std::error::Error;

pub fn create_pdf(
    path: &str,
    name: &str,
    total: f32,
    subjects: u32,
    average: f32,
    grade: &str,
) -> Result<(), Box<dyn Error>> {
    let (doc, page1, layer1) = PdfDocument::new("Student Report", Mm(210.0), Mm(297.0), "Layer 1");
    let font = doc.add_builtin_font(BuiltinFont::HelveticaBold)?;
    let font_bold = doc.add_builtin_font(BuiltinFont::HelveticaOblique)?;

    let layer = doc.get_page(page1).get_layer(layer1);

    // Header Bar
    let header = Line {
        points: vec![
            (Point::new(Mm(0.0), Mm(285.0)), false),
            (Point::new(Mm(210.0), Mm(285.0)), false),
        ],
        is_closed: false,
        has_fill: false,
        has_stroke: true,
        is_clipping_path: false,
    };
    layer.set_outline_color(Color::Rgb(Rgb::new(0.1, 0.3, 0.7, None)));
    layer.set_outline_thickness(25.0);
    layer.add_shape(header);

    // Title Text
    layer.begin_text_section();
    layer.set_font(&font, 18.0);
    layer.set_text_cursor(Mm(15.0), Mm(275.0));
    layer.set_line_height(20.0);
    layer.write_text("🏫 Blockseblock", &font);
    layer.add_line_break();
    layer.write_text("📘 Student Performance Report", &font);
    layer.end_text_section();

    // Student Data Section
    layer.begin_text_section();
    layer.set_font(&font_bold, 12.0);
    layer.set_text_cursor(Mm(20.0), Mm(245.0));
    layer.set_line_height(18.0);
    layer.write_text(&format!("👤 Name: {}", name), &font_bold);
    layer.add_line_break();
    layer.write_text(&format!("🧮 Total Marks: {}", total), &font_bold);
    layer.add_line_break();
    layer.write_text(&format!("📚 Subjects: {}", subjects), &font_bold);
    layer.add_line_break();
    layer.write_text(&format!("📊 Average: {:.2}", average), &font_bold);
    layer.add_line_break();

    // Grade with color
    let grade_color = match grade {
        "A" => Rgb::new(0.0, 0.6, 0.1, None),   // Green
        "B" => Rgb::new(0.2, 0.5, 0.9, None),   // Blue
        "C" => Rgb::new(1.0, 0.65, 0.0, None),  // Orange
        _   => Rgb::new(0.8, 0.0, 0.0, None),   // Red
    };

    layer.set_fill_color(Color::Rgb(grade_color));
    layer.write_text(&format!("🏅 Grade: {}", grade), &font_bold);
    layer.end_text_section();

    // Footer
    layer.begin_text_section();
    layer.set_font(&font, 10.0);
    layer.set_text_cursor(Mm(20.0), Mm(30.0));
    layer.write_text("Generated by Yuvraj Kumar • Blockseblock", &font);
    layer.end_text_section();

    let mut file = BufWriter::new(File::create(path)?);
    doc.save(&mut file)?;

    Ok(())
}
